### ISSUE TITLE
always api error

### ISSUE THREAD

**Issue by Archaeus** [nfarina/homebridge-tesla#101]
i'm a chinese guy,my tesla token is not work this ,i dont konw how to solve,hope nfarina have a look soon

**Comment by Archaeus** [comment]
<img width="1297" alt="截屏2022-12-10 16 52 37" src="https://user-images.githubusercontent.com/36544054/206842135-0b1dde82-a856-44de-a840-44a0c3164783.png">

**Comment by Archaeus** [comment]
[Tesla Model Y] Error while getting an access token: Authentication has previously failed; not retrying.
[12/10/2022, 11:40:14 PM] [Tesla Model Y] Error while getting an access token: Authentication has previously failed; not retrying.
[12/10/2022, 11:40:14 PM] Error: invalid_request
    at _callee2$ (/homebridge/node_modules/homebridge-tesla/dist/index.js:2324:21)
    at tryCatch (/homebridge/node_modules/homebridge-tesla/dist/index.js:44:17)
    at Generator.<anonymous> (/homebridge/node_modules/homebridge-tesla/dist/index.js:125:22)
    at Generator.next (/homebridge/node_modules/homebridge-tesla/dist/index.js:69:21)
    at asyncGeneratorStep (/homebridge/node_modules/homebridge-tesla/dist/index.js:311:24)
    at _next (/homebridge/node_modules/homebridge-tesla/dist/index.js:330:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by nfarina** [comment]
Hmm perhaps Tesla has a different auth server (or different API servers entirely) in China? Unfortunately hard for me to fix since I can't reproduce it here :(

**Comment by Archaeus** [comment]
one guy tell me fix api gatewat in index.js,but i cant find where fix in index.js,there are many
 codes,its difficult for me

**Comment by nfarina** [comment]
I've published version 4.0.2 which might fix this for you - in the configuration, try setting the "china" option to true.

**Comment by Archaeus** [comment]
ahhhhhhhh，its ok，thank you very much，i can control my model y on my iPhone。
