### ISSUE TITLE
TeslaJS error: Too Many Requests

### ISSUE THREAD

**Issue by Frank-Friemel** [nfarina/homebridge-tesla#121]
Hi!

First of all: thanks, for the Plug-In. It's great (and also is my Model 3). Got the Plug-In running for a month now. But today it started throwing errors (log attached):

[6.12.2023, 09:40:23] [Tesla] Exchanging refresh token for an access token…
[6.12.2023, 09:40:23] [Tesla] Got an access token.
[6.12.2023, 09:40:23] [Tesla] Exchanging refresh token for an access token…
[6.12.2023, 09:40:23] [Tesla] Got an access token.
TeslaJS error: Too Many Requests

Here's my homebridge infos:

OS	 Raspbian GNU/Linux Buster (10)
User	homebridge
Node.js Version	 v18.17.1
Node.js Path	/usr/bin
storage-path:	/var/lib/homebridge
config-path:	/var/lib/homebridge/config.json
Pluginpfad	/usr/lib/node_modules

[homebridge.log.txt](https://github.com/nfarina/homebridge-tesla/files/13589283/homebridge.log.txt)

**Comment by jeredfloyd** [comment]
Adding to this, when I get this error it is considered fatal to Homebridge and kills the entire instance (which then loops and restarts) rather than just disabling the plugin:

```
[12/6/2023, 1:26:01 PM] [Tesla] Exchanging refresh token for an access token…
[12/6/2023, 1:26:01 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 8492) is running on port 51912.
[12/6/2023, 1:26:01 PM] [Tesla] Got an access token.
[12/6/2023, 1:26:01 PM] [Tesla] Exchanging refresh token for an access token…
[12/6/2023, 1:26:02 PM] [Tesla] Got an access token.
TeslaJS error: Too Many Requests
[12/6/2023, 1:26:02 PM] Error: Too Many Requests
    at _callee9$ (/usr/lib/node_modules/homebridge-tesla/dist/index.js:2998:23)
    at tryCatch (/usr/lib/node_modules/homebridge-tesla/dist/index.js:44:17)
    at Generator.<anonymous> (/usr/lib/node_modules/homebridge-tesla/dist/index.js:125:22)
    at Generator.throw (/usr/lib/node_modules/homebridge-tesla/dist/index.js:69:21)
    at asyncGeneratorStep (/usr/lib/node_modules/homebridge-tesla/dist/index.js:311:24)
    at _throw (/usr/lib/node_modules/homebridge-tesla/dist/index.js:333:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/6/2023, 1:26:02 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by gielk** [comment]
I encountered the same problem two days ago. I had to disable the child bridge that was running, as it was continuously rebooting.

**Comment by LukeStephen** [comment]
I am seeing this too, causing homebridge into a restart loop. Had to disable to stop it...

I have Two Tesla's on my account now, is that causing this?

Anything I can do to fix this?

**Comment by Frank-Friemel** [comment]
Unfortunately not. Please take a look at latest change to the „Readme.md“
