### ISSUE TITLE
Tesla homebridge not working with Precondition Failed Error

### ISSUE THREAD

**Issue by luvmex** [nfarina/homebridge-tesla#129]
Suddenly the Tesla on Homebridge all got "no response" status.
I tried to restart the home bridge, but it was still not working.

I have generated the new API through: https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613
But I still get the problem as the below error.

```
TeslaJS error: Precondition Failed
Error: Precondition Failed
    at _callee9$ (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:2998:23)
    at tryCatch (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:44:17)
    at Generator.<anonymous> (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:125:22)
    at Generator.throw (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:69:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:311:24)
    at _throw (/usr/local/lib/node_modules/homebridge-tesla/dist/index.js:333:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Stewart06** [comment]
Pareil pour moi aussi !!!
Ça devient de moins en moins fiable quand même.

**Comment by antoine101009** [comment]
idem :(

**Comment by nfarina** [comment]
Sorry guys, this is all because Tesla has removed their (unofficial) REST API that most 3rd party apps use. More info here: https://github.com/nfarina/homebridge-tesla/issues/116#issuecomment-1843743301

I am waiting to see if there is a path forward for users to control their own cars without someone paying Tesla for access.

**Comment by nfarina** [comment]
Unfortunately not yet - see this comment for the reasons why: https://github.com/nfarina/homebridge-tesla/issues/116#issuecomment-1841890412

**Comment by nfarina** [comment]
Closing all issues related to this in favor of #116 so we can centralize discussion.
