### ISSUE TITLE
Plugin constantly crashing recently

### ISSUE THREAD

**Issue by KE55ARD** [nfarina/homebridge-tesla#131]
The plugin on my Homebridge instance has shown "no response" for about a week now and I finally got around to checking the logs and see the following happening repeatedly.

`[30/01/2024, 11:12:34] [Ted] Got an access token.
TeslaJS error: Precondition Failed
/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:2998
              error = new Error(_context9.t0);
                      ^
Error: Precondition Failed
    at _callee9$ (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:2998:23)
    at tryCatch (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:44:17)
    at Generator.<anonymous> (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:125:22)
    at Generator.throw (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:69:21)
    at asyncGeneratorStep (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:311:24)
    at _throw (/var/lib/homebridge/node_modules/homebridge-tesla/dist/index.js:333:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[30/01/2024, 11:12:34] [Ted] Child bridge process ended`

Any idea why this is suddenly happening?

**Comment by nfarina** [comment]
Hi, so sorry about this, see #116 for context.
