### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by Jasonlightman** [nfarina/homebridge-tesla#30]
Hi I just installed this plugin with:
 npm install homebridge-tesla 

 and when I put the details in the config file and start Homebridge I get this error,

Error: The requested accessory 'Tesla' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11

Any help would be great,

Thank you,
Jason

**Comment by nfarina** [comment]
Hello! It sounds like Homebridge isn't finding and loading the Tesla plugin. Typically Homebridge plugins are installed globally - `sudo npm install -g homebridge-tesla` for instance.

**Comment by Jasonlightman** [comment]
Hi Nfarina,
 Thank you for the quick response! That was it! do you know if there are any plans to add command to vent/close windows that was recently added?

Thanks ,
Jason

**Comment by nfarina** [comment]
That would be cool! Probably easy to add. Just need to check if TeslaJS supports that command yet.

**Comment by Jasonlightman** [comment]
Looks like they added it in 4.4.0
"In 4.4.0 added windowControl interface"
