### ISSUE TITLE
Login Issues with Username/Password

### ISSUE THREAD

**Issue by digivish** [nfarina/homebridge-tesla#63]
Getting this error repeatedly today. Not using authToken - only username and password

[2/17/2021, 12:10:19 PM] [Car3] Logging into Tesla with username/password…
TeslaJS error: TypeError: Cannot read property 'forEach' of null
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/teslajs/src/auth.js:51:26
    at tryCallOne (/usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/homebridge-tesla/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:75:11)

**Comment by nfarina** [comment]
Are you able to try version `2.5.3`?

**Comment by digivish** [comment]
Yes, just reinstalled 2.5.3 thank you. Not seeing the login error.

**Comment by rhdny** [comment]
For what's it worth, I see the same error at the beginning of my login sequence but I eventually get logged in. However I see TeslaJS 500 and 540 errors when accessing any services beyond the car online accessory.

**Comment by rhdny** [comment]
Set up a clean environment and only installed homebridge-tesla. Here's what I'm getting:

[2/20/2021, 10:12:51 PM] [Model S] Logging into Tesla with username/password…
[2/20/2021, 10:13:19 PM] [Model S] Logging into Tesla with username/password…
[2/20/2021, 10:13:19 PM] [Model S] Logging into Tesla with username/password…
[2/20/2021, 10:13:19 PM] [Model S] Logging into Tesla with username/password…
[2/20/2021, 10:13:19 PM] [Model S] Logging into Tesla with username/password…
[2/20/2021, 10:13:19 PM] [Model S] Logging into Tesla with username/password…
TeslaJS error: TypeError: Cannot read property 'forEach' of null
    at /homebridge/node_modules/homebridge-tesla/node_modules/teslajs/src/auth.js:51:26
    at tryCallOne (/homebridge/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:37:12)
    at /homebridge/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:123:15
    at flush (/homebridge/node_modules/homebridge-tesla/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error repeats...

**Comment by mavantix** [comment]
I'm also experiencing this problem with a brand new Ubuntu 20.02.4 server running latest HOOBS.

Interestingly, generate-tesla-token just hangs trying to make a token as well. I wonder if tesla.com is blocking the https requests based on user agent or something?

**Comment by rhdny** [comment]
I believe I was getting blocked by Tesla's WAF. I gave up on it for a bit and recently tried again via a HA plugin. Back in business now.

**Comment by nfarina** [comment]
This should be fixed by the latest version (3.0.1) - check the README for details!
