### ISSUE TITLE
All Accessories No Response after update to v2.6.0

### ISSUE THREAD

**Issue by luvmex** [nfarina/homebridge-tesla#72]
As the title,
All config is all the same(Authorize with the token),
After an update v2.6.0 the Homebrige log show as: "TeslaJS error: Unauthorized".
And when I try to reverse to the old version as 2.5.2, still not work... but no showing the log as "TeslaJS error: Unauthorized".

---

And if try with the "username/password" to login the log as below:

TeslaJS error: Error: Login credentials rejected
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/teslajs/src/auth.js:93:19
    at tryCallOne (/usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/homebridge-tesla/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

---

Any tips to solve? 
Thanks

**Comment by luvmex** [comment]
It seems my old token has been expired, and the "generate tesla token" is no working for me, which means both methods are print the same errors. I'm not sure the relation between.

So I try the alternative way by downloading the iOS app "AuthAppForTesla" and generating the new token, and it works.
