### ISSUE TITLE
username and password being rejected - v2.6.0 on Pi

### ISSUE THREAD

**Issue by dssanton** [nfarina/homebridge-tesla#78]
TeslaJS error: Error: Login credentials rejected
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/teslajs/src/auth.js:95:19
    at tryCallOne (/usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/homebridge-tesla/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/homebridge-tesla/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Confirmed valid on tesla app and website. Name, VIN match to app.

**Comment by nfarina** [comment]
This should be fixed by the latest version (3.0.1) - check the README for details!
